[package]
name = "embedded-audio"
version = "0.0.0"
edition = "2021"
authors = ["Decaday <myDecaday@outlook.com>"]
repository = "https://github.com/decaday/embedded-audio"
documentation = "https://docs.rs/embedded-audio-driver"
homepage = "https://github.com/decaday/embedded-audio"
categories = ["embedded", "no-std", "hardware-support"]
description = "Embedded Audio Driver"
readme = "../README.md"
license = "Apache-2.0"

[dependencies]
defmt = { version = "0.3", optional = true }
embedded-audio-driver = { path = "../embedded-audio-driver" }

[features]
defmt = ["dep:defmt"]